version: '3.8'
services:
  frontend:
    build: ./manage-mart-frontend
    depends_on:
      - backend
    restart: always

  backend:
    build: ./manage-mart-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always
  
  db:
    image: mysql:8
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=managemart
    ports:
      - "3306:3306"
    volumes:
      - ../mysql_data:/var/lib/mysql
      - ./dbscript.sql:/docker-entrypoint-initdb.d/init.sql

  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

volumes:
  mysql_data:
